### PR TITLE
ad-hoc clean-up

### PR DESCRIPTION
**Pull request by EpicMaxKanensley**
Misc. changes made while performing initial review. Bundled as a circumstantial exception to the rule about PR granularity.

### CODE REVIEW

**Comment by EpicMaxKanensley** [comment]
This seems to have grabbed the spurious build failure on the previous one.  Perhaps because the title is the same?  I'll try one more time.

**Comment by EpicMaxKanensley** [comment]
@w4bremer The 5.2 build failed because the docker registry hit a rate limit. I created a new PR but it's picking up on the build failure from the previous one because the commit hash is still the same.  Is there a way to force it to re-run?

**Comment by w4bremer** [comment]
> @w4bremer The 5.2 build failed because the docker registry hit a rate limit. I created a new PR but it's picking up on the build failure from the previous one because the commit hash is still the same. Is there a way to force it to re-run?

@EpicMaxKanensley no, currently I don't have a simple way to re-run it, if the CI itself fails for other reason. Should not be complicated to add. Right now, we can only reset the internal state. This will then re-run all tests for all open PRs.

**Comment by w4bremer** [comment]
Manually re-run the missing Linux build tests and tested against 4.27, 5.5 on Windows. All successful.

**Pull request merged**
